# This workflow takes care of building and publishing the source code of the Danish Public Libraries CMS.
name: Translate source
on:
  pull_request:
  push:
    branches:
      - translation-gh-action-test
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Install go-task
      uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup site
      run: task ci:reset
    - name: Scan translations
      run: LANGUAGE=da task translations:build:source
    - name: Commit translations
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: './web/profiles/dpl_cms/translation_source/*.po'
        commit_message: New translations were found
    - name: Publish translations to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/profiles/dpl_cms/translations
        destination_dir: translations
    - name: Make Poeditor look for changes
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: https://api.poeditor.com/webhooks/f233af2e4a
        webhook_secret: 'xxxx'
